# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# resources:
#   repositories:
  # - repository: FhirCodegen # The name used to reference this repository in the checkout step
  #   type: github
  #   name: MyGitHubOrgOrUser/MyGitHubRepo

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- checkout: github://microsoft/fhir-codegen.git@dev


# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
